A lot of reworking in common and build-pkg in order to make it work. Added scripts for 6.17-6.20

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -8,37 +8,32 @@ function _echo_err() {
    echo -e "\e[31m ${@} \e[0m"
 }
 
-function _exec() {
-    CMD=${@}
-    __run_cmd ${CMD}
-}
-
 function __configure() {
     CMD="../configure ${@}"
-    __run_cmd ${CMD}
+    _exec ${CMD}
 }
 
 function _configure() {
     CMD="./configure ${@}"
-    __run_cmd ${CMD}
+    _exec ${CMD}
 }
 
 function _make () {
     CMD="make -j${MAKE_JOBS_NUM} ${@}"
-    __run_cmd ${CMD}
+    _exec ${CMD}
 }
 
 function _make_check() {
     CMD="make -j ${MAKE_JOBS_NUM} check ${@}"
-    __run_cmd ${CMD}
+    _exec ${CMD}
 }
 
-function __run_cmd() {
-    ¦   LOG=${SCRIPT_DIR}/logs/${CUR_PACK}.tmp.log
+function _exec() {
+    LOG=${SCRIPT_DIR}/logs/${CUR_PACK}.tmp.log
     LOG_ERR=${SCRIPT_DIR}/logs/${CUR_PACK}.tmp.err
 
     echo ${@}
-    { ${@} ;} >>${LOG} 2>>${LOG_ERR} || {_echo_err "Failed" ; exit 1;}
+    eval ${@} 1>>${LOG} 2>>${LOG_ERR} || { _echo_err "Failed" ; exit 1; }
 }
 
 export -f _echo_err     \
@@ -47,4 +42,4 @@ export -f _echo_err     \
         _configure      \
         __configure     \
         _make           \
-        _make_check
+        _make_check     
